disableKinds = ["taxonomy", "taxonomyTerm"]

# directories
archetypeDir = "archetypes"
dataDir = "site/data"
contentDir = "site/content"
staticDir = "site/static"
layoutDir = "site/layouts"
publishDir = "build"

# site
languageCode = "en"
baseURL = "http://imscraping.ninja/"
title = "Web Scraping and Data Mining Service"

[menu]
  [[menu.header]]
    name = "Tech"
    weight = 1
    url = "/tech/"
  [[menu.header]]
    name = "Services"
    weight = 2
    url = "/services/"
