# default lanugage
languageCode = "en-us"
defaultContentLanguage = "en"

# disable RSS
disableRSS = true

# Highlight
PygmentsCodeFences = true
pygmentsstyle = "emacs"

# don't need yet
disableKinds = ["taxonomy", "taxonomyTerm", "category", "tag"]

# directories
archetypeDir = "site/archetypes"
dataDir = "site/data"
contentDir = "site/content"
staticDir = "site/static"
layoutDir = "site/layouts"
publishDir = "build"

# site
baseURL = "http://www.imscraping.ninja/"
title = "Web Scraping and Data Mining Service"

[menu]
  [[menu.header]]
    name = "Tech"
    weight = 1
    url = "/tech/"
  [[menu.header]]
    name = "Services"
    weight = 2
    url = "/services/"
  [[menu.header]]
    name = "Projects"
    weight = 3
    url = "/projects/"
  [[menu.header]]
    name = "Posts"
    weight = 4
    url = "/posts/"
