baseURL = "http://imscraping.ninja/"
languageCode = "en"
title = "Web Scraping and Data Mining Service"

[menu]
  [[menu.header]]
    name = "Tech"
    weight = 1
    url = "/tech/"
  [[menu.header]]
    name = "Services"
    weight = 2
    url = "/services/"
